#!/usr/bin/env python3
"""Create private runtime external-model configs for multi-model-review."""

from __future__ import annotations

import getpass
import json
import re
from pathlib import Path


SKILL_ROOT = Path(__file__).resolve().parent.parent
LOCAL_ENV_PATH = SKILL_ROOT / ".env.local"
RUNTIME_DIR = SKILL_ROOT / ".runtime"
REVIEWERS_PATH = RUNTIME_DIR / "external-reviewers.json"
JUDGES_PATH = RUNTIME_DIR / "external-judges.json"


def prompt_text(label: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default


def env_key(name: str, index: int) -> str:
    normalized = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").upper()
    if not normalized:
        normalized = f"MODEL_{index}"
    return f"MMR_{normalized}_API_KEY"


def read_existing_env() -> dict[str, str]:
    values: dict[str, str] = {}
    if not LOCAL_ENV_PATH.is_file():
        return values
    for raw_line in LOCAL_ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def write_env(values: dict[str, str]) -> None:
    lines = [
        "# Private API keys for multi-model-review external reviewers.",
        "# Generated by scripts/configure_external_models.py.",
    ]
    for key in sorted(values):
        lines.append(f"{key}={values[key]}")
    LOCAL_ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    LOCAL_ENV_PATH.chmod(0o600)


def reviewer_config(
    name: str,
    endpoint: str,
    model: str,
    api_key_env: str,
    prompt_id: str,
    max_tokens: int,
    temperature: float,
) -> dict[str, object]:
    return {
        "name": name,
        "enabled": True,
        "endpoint": endpoint,
        "model": model,
        "api_key_env": api_key_env,
        "prompt_id": prompt_id,
        "max_tokens": max_tokens,
        "temperature": temperature,
        "timeout_seconds": 180,
    }


def main() -> int:
    print("Configure two or three OpenAI-compatible external models.")
    print("API keys are written only to .env.local; JSON configs store env names.")
    print()

    count_text = prompt_text("number of external models, 2 for hybrid or 3 for external", "2")
    while count_text not in {"2", "3"}:
        count_text = prompt_text("number of external models, 2 for hybrid or 3 for external", "2")
    model_count = int(count_text)

    prompt_cycle = [
        ("glm", "correctness-review"),
        ("deepseek", "testing-review"),
        ("claude", "adversarial-review"),
    ]
    models: list[dict[str, str]] = []
    existing_env = read_existing_env()

    for index, (default_name, default_prompt_id) in enumerate(
        prompt_cycle[:model_count], start=1
    ):
        print(f"Model {index}")
        name = prompt_text("  name", default_name)
        endpoint = prompt_text("  url")
        model = prompt_text("  model")
        key_name = env_key(name, index)
        current_value = existing_env.get(key_name)
        key_prompt = f"  api key for {key_name}"
        if current_value:
            api_key = getpass.getpass(f"{key_prompt} [press Enter to keep existing]: ")
            api_key = api_key.strip() or current_value
        else:
            api_key = getpass.getpass(f"{key_prompt}: ").strip()
            while not api_key:
                api_key = getpass.getpass(f"{key_prompt}: ").strip()
        existing_env[key_name] = api_key
        models.append(
            {
                "name": name,
                "endpoint": endpoint,
                "model": model,
                "api_key_env": key_name,
                "prompt_id": default_prompt_id,
            }
        )
        print()

    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    write_env(existing_env)

    reviewers = [
        reviewer_config(
            name=f"{model['name']}-{model['prompt_id'].removesuffix('-review')}",
            endpoint=model["endpoint"],
            model=model["model"],
            api_key_env=model["api_key_env"],
            prompt_id=model["prompt_id"],
            max_tokens=8192,
            temperature=0.2,
        )
        for model in models
    ]
    judges = [
        reviewer_config(
            name=f"{model['name']}-judge",
            endpoint=model["endpoint"],
            model=model["model"],
            api_key_env=model["api_key_env"],
            prompt_id="judge-review",
            max_tokens=4096,
            temperature=0.1,
        )
        for model in models
    ]

    REVIEWERS_PATH.write_text(
        json.dumps({"reviewers": reviewers}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    JUDGES_PATH.write_text(
        json.dumps({"reviewers": judges}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    print(f"Wrote API keys: {LOCAL_ENV_PATH}")
    print(f"Wrote reviewers: {REVIEWERS_PATH}")
    print(f"Wrote judges: {JUDGES_PATH}")
    print()
    print("Use these configs when asking Codex for multi-model-review hybrid or external.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
